export interface RequestCardProps {
    backdrop_path: string,
    id: number,
    title: string,
    subtitle: string,
    original_title: string,
    name: string,
    original_name: string,
    original_language: string,
    overview: string,
    poster_path: string,
    media_type: string,
    adult: boolean,
    genre_ids: number[],
    popularity: number,
    release_date: string,
    video: boolean,
    vote_average: number,
    vote_count: number,
}