import Head from "next/head";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import CardContainer from "@/components/CardContainer";
import Footer from "@/components/Footer";
import WatchLater from "@/components/modals/WatchLater";
import { useState } from "react";
import Top from "@/components/Top";

import styles from "@/styles/Home.module.scss";

const inter = Inter({ subsets: ["latin"] });


export default function Home() {
  const [visible, setVisible] = useState(false)
  const [movieTitle, setMovieTitle] = useState<string | null>(null)
  const [movieSubTitle, setMovieSubTitle] = useState<string | null>(null)

  function handleCloseModalWatchLater() {
    setVisible(false);
  }
  function handleOpenModalWatchLater(title: string, subTitle?: string) {
    setMovieTitle(title)
    if (subTitle && subTitle !== "") {
      setMovieSubTitle(subTitle)
    }
    setVisible(true)
  }

  return (
    <>
      <Head>
        <title>FlixNext - Início</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.content}>
          <Header />
          <Top />
          <div className={styles.mid}>
            <CardContainer
              handleOpenModal={handleOpenModalWatchLater}
              section="ação"
            />
            <CardContainer
              handleOpenModal={handleOpenModalWatchLater}
              section="aventura"
            />

            <CardContainer
              handleOpenModal={handleOpenModalWatchLater}
              section="suspense"
            />
            <CardContainer
              handleOpenModal={handleOpenModalWatchLater}
              section="comédia"
            />
            <CardContainer
              handleOpenModal={handleOpenModalWatchLater}
              section="terror"
            />
            <CardContainer
              handleOpenModal={handleOpenModalWatchLater}
              section="drama"
            />
            <CardContainer
              handleOpenModal={handleOpenModalWatchLater}
              section="ficção científica"
            />

            <CardContainer
              handleOpenModal={handleOpenModalWatchLater}
              section="fantasia"
            />
            <CardContainer
              handleOpenModal={handleOpenModalWatchLater}
              section="romance"
            />
            <CardContainer
              handleOpenModal={handleOpenModalWatchLater}
              section="marvel"
            />
            <CardContainer
              handleOpenModal={handleOpenModalWatchLater}
              section="DC"
            />
            <CardContainer
              handleOpenModal={handleOpenModalWatchLater}
              section="animação"
            />

          </div>
          <Footer />
        </div>
        {visible && (
          <><WatchLater
            visible={handleCloseModalWatchLater}
            title={movieTitle}
            subTitle={movieSubTitle}
          /></>
        )}
      </main>
    </>
  );
}
