import Head from "next/head";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import CardContainer from "@/components/CardContainer";
import Footer from "@/components/Footer";
import WatchLater from "@/components/modals/WatchLater";
import { useEffect, useState } from "react";
import Top from "@/components/Top";

import styles from "@/styles/Home.module.scss";
import Search from "@/components/Searching";
import { getCookieClient } from "@/services/cookieClient";

const inter = Inter({ subsets: ["latin"] });


export default function Home() {
  const [visible, setVisible] = useState(false)
  const [movieTitle, setMovieTitle] = useState<string | null>(null)
  const [movieSubTitle, setMovieSubTitle] = useState<string | null>(null)
  const [cardPerContainer, setCardPerContainer] = useState<number>(5)
  const [width, setWidth] = useState<number>()

  const userData: { id: string, name: string, email: string, avatar: string, token: string, verified: boolean } = getCookieClient();
  console.log(userData)

  const divisaoPorGenero = [
    "ação",
    "aventura",
    "suspense",
    "comédia",
    "terror",
    "romance",
    "drama",
    "ficção científica",
    "fantasia",
    "marvel",
    "dc",
    "animação"
  ]

  useEffect(() => {
    function handleResize() {
      const width = window.innerWidth;
      //console.log(width)
      setWidth(width)

      // Ajustar os breakpoints depois
      if (width < 780) {
        setCardPerContainer(1)
      } else if (width < 1100) {
        setCardPerContainer(2)
      } else if (width < 1480) {
        setCardPerContainer(3)
      } else if (width < 1650) {
        setCardPerContainer(4)
      } else {
        setCardPerContainer(5)
      }

    }
    window.addEventListener('resize', handleResize)

    handleResize()

    return () => window.removeEventListener('resize', handleResize)
  }, [])
  useEffect(() => {

    const rightClickBlock = (event: MouseEvent) => {
      event.preventDefault();
    };

    // Impede atalhos de ferramentas de desenvolvedor
    const openConsoleBlock = (event: KeyboardEvent) => {

      if (
        event.key === 'F12' ||
        (event.ctrlKey && event.shiftKey && event.key === 'I') ||
        (event.ctrlKey && event.shiftKey && event.key === 'C') ||
        (event.ctrlKey && event.shiftKey && event.key === 'J') ||
        (event.ctrlKey && event.key === 'U')
      ) {
        event.preventDefault();
      }
    };

    document.addEventListener('contextmenu', rightClickBlock);
    document.addEventListener('keydown', openConsoleBlock);

    return () => {
      document.removeEventListener('contextmenu', rightClickBlock);
      document.removeEventListener('keydown', openConsoleBlock);
    };
  }, []);


  function handleCloseModalWatchLater() {
    setVisible(false);
  }
  function handleOpenModalWatchLater(title: string, subTitle?: string) {
    setMovieTitle(title)
    if (subTitle && subTitle !== "") {
      setMovieSubTitle(subTitle)
    }
    setVisible(true)
  }

  return (
    <>
      <Head>
        <title>FlixNext - Início</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.content}>
          <Header userAvatar={userData?.avatar} />
          <Top />
          <div className={styles.mid}>
            {divisaoPorGenero.map((sec, index) => (
              <div key={index}>
                <CardContainer
                  handleOpenModal={handleOpenModalWatchLater}
                  section={sec}
                  cardPerContainer={cardPerContainer}
                />
                {index === 1 && cardPerContainer >= 2 && <Search />}
              </div>

            )

            )}

          </div>
          <Footer />
        </div>
        {visible && (
          <><WatchLater
            visible={handleCloseModalWatchLater}
            title={movieTitle}
            subTitle={movieSubTitle}
          /></>
        )}
      </main>
    </>
  );
}
